apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice-serice
spec:
  type: LoadBalancer
  selector:
    app: simpletimeservice
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000